spring:
  application:
    name: jarvis-oss-service # 服务名
  profiles:
    active: dev # 环境标识
server:
  port: 6133
qiniu:
  access-key: "5KDvz7r9ptd-opVLyviNi8MJdlgwD8MWTC1LFW8g"
  secret-key: "Pn8Ws6Aw3Z7-uAHmZqy-KIgna8JbSXcLYNy-8rFw"
  bucket: "jarvis-oss-service-oversea"
  domain: "http://j-agent.xyz"